// Auto-generated by LibreLane
module ALU(
`ifdef USE_POWER_PINS
  inout VPWR,
  inout VGND,
`endif
  input[31:0] A,
  input[31:0] B,
  input[2:0] opCode,
  input[2:0] statusIn,
  output[31:0] y,
  output statusOut
);
endmodule
